# WARNING: This is an autogenerated plan. It may not behave as expected.
plan bolt_primer::third(
  TargetSpec $hello_hosts,
  TargetSpec $goodbye_hosts,
  $message
) {
  run_command('hostname', 'all', 'Get all hostnames')
  $hello_results = run_task('bolt_primer::hello', $hello_hosts, 'Say hello', { 'message' => $message })
  out::message($hello_results[0].value)
  $goodbye_results = run_task('bolt_primer::goodbye', $goodbye_hosts, 'Say goodbye', { 'message' => $message })
  out::message($goodbye_results[0].value)
}
